// <auto-generated />
using System;
using GoChat.DAL.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace GoChat.DAL.Migrations
{
    [DbContext(typeof(AppDbContex))]
    partial class AppDbContexModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("GoChat.DAL.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("AccessFailedCount");

                    b.Property<int?>("ChatsId");

                    b.Property<string>("ConcurrencyStamp");

                    b.Property<string>("Email");

                    b.Property<bool>("EmailConfirmed");

                    b.Property<bool>("LockoutEnabled");

                    b.Property<DateTimeOffset?>("LockoutEnd");

                    b.Property<string>("NormalizedEmail");

                    b.Property<string>("NormalizedUserName");

                    b.Property<string>("PasswordHash");

                    b.Property<string>("PhoneNumber");

                    b.Property<bool>("PhoneNumberConfirmed");

                    b.Property<string>("PhotoLocation");

                    b.Property<string>("SecurityStamp");

                    b.Property<bool>("TwoFactorEnabled");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("ChatsId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("GoChat.DAL.Entities.Chat", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Messages");

                    b.Property<int?>("UsersId");

                    b.HasKey("Id");

                    b.HasIndex("UsersId");

                    b.ToTable("Chats");
                });

            modelBuilder.Entity("GoChat.DAL.Entities.Friends", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("UserId");

                    b.Property<string>("who");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Friends");
                });

            modelBuilder.Entity("GoChat.DAL.Entities.PreChat", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.HasKey("Id");

                    b.ToTable("PreChat");
                });

            modelBuilder.Entity("GoChat.DAL.Entities.AppUser", b =>
                {
                    b.HasOne("GoChat.DAL.Entities.PreChat", "Chats")
                        .WithMany("User")
                        .HasForeignKey("ChatsId");
                });

            modelBuilder.Entity("GoChat.DAL.Entities.Chat", b =>
                {
                    b.HasOne("GoChat.DAL.Entities.PreChat", "Users")
                        .WithMany("ChatId")
                        .HasForeignKey("UsersId");
                });

            modelBuilder.Entity("GoChat.DAL.Entities.Friends", b =>
                {
                    b.HasOne("GoChat.DAL.Entities.AppUser", "User")
                        .WithMany("MyFriends")
                        .HasForeignKey("UserId");
                });
#pragma warning restore 612, 618
        }
    }
}
